version: "3.9"

services:
  api:
    build:
      context: .
    container_name: task_manager_api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
    restart: unless-stopped
