version: "3.9"

services:
  api:
    build:
      context: .
    container_name: task_manager_api_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
    restart: unless-stopped
